version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5052:80"         # Expose the app on localhost:5052
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"      # Expose Redis on localhost:6379
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
